baseURL = "http://example.org/"
languageCode = "en-us"
DefaultContentLanguage = "si"

[languages]
  [languages.si]
    title = "Hugo FRI spletna stran"
    weight = 0

  [languages.en]
    title = "Hugo FRI website"
    weight = 1
