DefaultContentLanguage = "sl"

[languages]
  [languages.sl]
    baseURL = "https://www-hugo.netlify.com/sl"
    contentDir = "content/sl"
    title = "Hugo FRI spletna stran"
    weight = 0
    languageCode = "sl-SI"
    [languages.sl.params]
      labPos = "predstojnik laboratorija"
      proj_types = [
        "EU projekti",
        "Bilateralni projekti",
        "Ostali mednarodni projekti",
        "Raziskovalni programi ARRS",
        "Raziskovalni projekti ARRS",
        "Projekti strukturnih skladov",
        "Ostali nacionalni projekti",
        "Tržni projekti"
      ]

  [languages.en]
    baseURL = "https://www-hugo.netlify.com/en"
    contentDir = "content/en"
    title = "Hugo FRI website"
    languageCode = "en-us"
    weight = 1
    [languages.en.params]
      labPos = "Head of Laboratory"
      proj_types = [
              "European projects",
              "Bilateral projects",
              "Ostali mednarodni projekti",
              "ARRS research programmes",
              "Research projects ARRS",
              "Projects Structural Funds",
              "Ostali nacionalni projekti",
              "Tržni projekti"
            ]
