languageCode = "en-us"
DefaultContentLanguage = "si"

[languages]
  [languages.si]
    baseURL = "https://www-hugo.netlify.com/-/si"
    contentDir = "content/si"
    title = "Hugo FRI spletna stran"
    weight = 0
    [languages.si.params]
      labPos = "predstojnik laboratorija"

  [languages.en]
    baseURL = "https://www-hugo.netlify.com/-/en"
    contentDir = "content/en"
    title = "Hugo FRI website"
    weight = 1
    [languages.en.params]
      labPos = "Head of Laboratory"
