DefaultContentLanguage = "sl"

[languages]
  [languages.sl]
    baseURL = "https://www-hugo.netlify.com/sl"
    contentDir = "content/sl"
    title = "Hugo FRI spletna stran"
    weight = 0
    languageCode = "sl-SI"
    [languages.sl.params]
      labPos = "predstojnik laboratorija"

  [languages.en]
    baseURL = "https://www-hugo.netlify.com/en"
    contentDir = "content/en"
    title = "Hugo FRI website"
    languageCode = "en-us"
    weight = 1
    [languages.en.params]
      labPos = "Head of Laboratory"
