DefaultContentLanguage = "sl"
[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.sl]
    languageName = "Slovenščina"
    baseURL = "https://www-hugo.netlify.com/hugo/sl"
    contentDir = "content/sl"
    title = "Hugo FRI spletna stran"
    weight = 0
    languageCode = "sl"
    [languages.sl.params]
      proj_types = [
        "EU projekti",
        "Bilateralni projekti",
        "Ostali mednarodni projekti",
        "Raziskovalni programi ARRS",
        "Raziskovalni projekti ARRS",
        "Projekti strukturnih skladov",
        "Ostali nacionalni projekti",
        "Tržni projekti"
      ]
    [languages.sl.permalinks]
        osebje = "/o-fakulteti/osebje/:slug"
        laboratorij = "/laboratorij/:filename"

  [languages.en]
    languageName = "English"
    baseURL = "https://www-hugo.netlify.com/hugo/en"
    contentDir = "content/en"
    title = "Hugo FRI website"
    languageCode = "en-US"
    weight = 1
    [languages.en.params]
      proj_types = [
              "European projects",
              "Bilateral projects",
              "Ostali mednarodni projekti",
              "ARRS research programmes",
              "Research projects ARRS",
              "Projects Structural Funds",
              "Ostali nacionalni projekti",
              "Tržni projekti"
            ]
    [languages.en.permalinks]
        osebje = "/employees/:slug"
        laboratorij = "/laboratory/:filename"
