[build]
publish = "public"
command = "hugo --minify -b $URL"

[build.environment]
HUGO_VERSION = "0.55.6"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/-/sl"
  status = 301
  force = true
